---
layout: cv
title: Tucker Trost
---
# Tucker Trost  
📞 (971) 420-5397 | 📧 [tuckertrost16@gmail.com](mailto:tuckertrost16@gmail.com)  
🔗 [LinkedIn](https://linkedin.com/in/tuckertrost) | 🌐 [tuckertrostbyui.github.io](https://tuckertrostbyui.github.io)

---

## EDUCATION  
**Bachelor of Science, Data Science**  
Brigham Young University - Idaho — *Rexburg, Idaho*  
*February 2025 – April 2025*  
Relevant Courses: Machine Learning, Data Visualization, Data Wrangling, Statistics, SQL, Python, R, Pyspark  
Societies/Clubs: President of the Data Science Society  

---

## EXPERIENCE

**Data Analyst, Student Records and Registration**  
Brigham Young University-Idaho — *Idaho*  
*October 2024 – Present*  
- Built and maintained a records retention Power BI Dashboard identifying over 400,000 student records ready for disposal  
- Utilized SQL to pull data from multiple sources to pipeline into dashboard for automation  
- Presented dashboard updates to executives biweekly for feedback and stakeholder alignment  

**Data Science Consultant, BYU-I Career Center**  
Brigham Young University-Idaho — *Idaho*  
*April 2025 – Present*  
- Built an end-to-end data pipeline and Power BI dashboard to track alumni career outcomes  
- Wrote SQL and Python code to pull, clean, and process data from multiple sources, including NLP on job titles  
- Met regularly with stakeholders to align on goals, share updates, and deliver actionable insights  

**Project Manager, Data Science Society**  
Brigham Young University-Idaho — *Idaho*  
*January 2025 – April 2025*  
- Led a team of data scientists using a SQL Database to house data for an attendance analytics project for the Pioneer Baseball League  
- Created compelling Data Visualizations in Python for stakeholders  
- Met once a month with league commissioner to communicate insights and receive feedback  

**Data Science Tutor/Teaching Assistant**  
Brigham Young University-Idaho — *Idaho*  
*January 2025 – April 2025*  
- Guided students of all skill levels in Python, SQL, R, Tableau, and Power BI  
- Broke down data wrangling and visualization concepts to enhance comprehension beyond assignments  
- Adapted explanations to diverse learning styles, fostering problem-solving skills and confidence in data analysis  

---

## SKILLS  
**Analysis/Visualization**: Python (Pandas, Lets-Plot, plotly, Pyspark), R (ggplot, tidyverse), Power BI (DAX), Tableau  
**Machine Learning**: Scikit-learn, TensorFlow, Random Forest Classifiers, Neural Networks, XGBoost  
**Database Management/Design**: MySQL, SQLite, Databricks, DAX Studio, Microsoft SQL Server  

---

## PROJECTS  

**Student Records Retention Compliance Dashboard**  
*October 2024 – Present*  
- Developed a Power BI model that identified over 200,000 student records ready for disposal to comply with AACRAO retention guidelines  
- Wrangled and cleaned data from 5 different databases to implement into the Power BI Model  

**Portland Crime Forecasting with XGBoost**  
*April 2025*  
- Trained an XGBoost model to predict daily Portland, Oregon crime counts with an R² score of 0.62  
- Applied feature engineering, hyperparameter tuning, and model evaluation with Python to improve prediction accuracy and reveal crime patterns  






<!-- ### Footer

Last updated: May 2013 -->